name: linn-jupyter-site-template-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If git submodules were used, uncomment next line
          # submodules: true

      - name: Install specific notebook version
        run: pip3 install notebook==6.4.12

      - name: Install nbconvert and nbextensions
        run: pip3 install nbconvert jupyter_contrib_nbextensions

      - name: Downgrade MarkupSafe
        run: pip3 install MarkupSafe==2.0.0 --force-reinstall

      - name: Convert ipynb to markdown of root
        run: jupyter nbconvert *.ipynb --to markdown
        continue-on-error: true

      - name: Convert ipynb to markdown of subfolders
        run: jupyter nbconvert **/*.ipynb --to markdown
        continue-on-error: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
